detectors:
  IrresponsibleModule:
    enabled: false

  DuplicateMethodCall:
    enabled: false

  UtilityFunction:
    public_methods_only: true

  TooManyMethods:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  TooManyStatements:
    enabled: false

  TooManyInstanceVariables:
    enabled: false
