AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Max: 50

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
