Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.  
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

AllCops:
    Exclude:
    - 'Server/app/views/**/*'
    - 'Server/app/assets/**/*'
    - 'Server/bin/*'
    - 'Server/db/schema.rb'
    - 'Server/db/migrate/*'
    - 'Server/log/**/*'
    - 'Server/test/**/*'
    - 'Server/node_modules/**/*'
    - 'Server/public/**/*'
    - 'Server/scripts/**/*'
    - 'Server/vendor/**/*'
    - 'Server/tmp/**/*'
    - '.git/**/*'
